# This is a basic workflow to help you get started with Actions
name: windows-build

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
    - name: package binaries
      run: |
        msbuild -p:Configuration=Release BGIinsert/BGIinsert.vcxproj
    - name: Test
      run: |
        tree
        
